/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  tutorialSidebar: [
    'index',
    'pages',
    'modules',
    'codeeditor',
    'shortcuts'
  ],
  customExtensions: [{ type: 'autogenerated', dirName: 'development/extensions' }],
  extensions: [{ type: 'autogenerated', dirName: 'extensions' }],
  saveFormat: [{ type: 'autogenerated', dirName: 'save-format' }],
  blocks: [
    { type: 'autogenerated', dirName: 'blocks' },
    'username',
  ],
};

export default sidebars;
